### PR TITLE
Add port to KAS in preparation for HyperShift migration

### PR DESCRIPTION
**Pull request by rtheis**

### CODE REVIEW

**Comment by rtheis** [comment]
**Toolkit KAS Service Example:**

```
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: master-cqpoicr10qaf7166b3qg
spec:
  clusterIP: 172.19.142.238
  clusterIPs:
  - 172.19.142.238
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30213
    port: 2040
    protocol: TCP
    targetPort: 2040
  selector:
    app: kube-apiserver
  sessionAffinity: None
  type: NodePort
```

**Comment by rtheis** [comment]
See https://github.ibm.com/alchemy-containers/armada-update/issues/5438#issuecomment-87487174 for test results.

**Review by jonesbr17 — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
