### PR TITLE
Fix config observer updates

### PR DESCRIPTION
**Pull request by csrwng**
Fixes a bug in the merge functions for both openshift apiserver and openshift controller manager configuration.
The merge was not doing a delete of existing keys if the key was not present in the update, causing continuous updates.
Adds unit test functions that verify that config observation is working as expected. 
Unit tests require the kubernetes go-client fake packages. That is added in a separate commit.

### CODE REVIEW

**Review by jmcmeek — APPROVED** [review]
lgtm

**Review by rtheis — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
