### PR TITLE
Set/Update tls-cipher-suites (1.2) for components

### PR DESCRIPTION
**Pull request by shalver**
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2036

### CODE REVIEW

**Comment by csrwng** [comment]
/ok-to-test
@shalver does this only apply to 4.5? (or newer version as well?)

**Comment by shalver** [comment]
Our intention is to make changes for 4.6+ as well;   but those versions will use 1.3 ciipher suites

**Review by rtheis — COMMENTED** [review]
Thanks Steve.

**Comment by csrwng** [comment]
@shalver you'll need to do a manual backport to 4.4 since it doesn't merge cleanly.

**Pull request merged**
