### PR TITLE
reconfigure route-controller-manager deployment

### PR DESCRIPTION
**Pull request by Evan-Reilly**
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/4900

### CODE REVIEW

**Review by rtheis — CHANGES_REQUESTED** [review]
Please regen the bindata

**Comment by Evan-Reilly** [comment]
Investigating why running that command doesn't work for me anymore..
```
evanreilly@Evans-MacBook-Pro ibm-roks-toolkit % make bindata
hack/update-generated-bindata.sh
hack/update-generated-bindata.sh: line 16: /var/folders/x2/kpvwj3195xbgmjty3blbr6l40000gn/T/tmp.BfYZYTlR/bin/go-bindata: No such file or directory
make: *** [bindata] Error 1
```

**Review by rtheis — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
