### PR TITLE
Add/Update tls-cipher-suites (1.3) for components

### PR DESCRIPTION
**Pull request by shalver**
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2036

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by rtheis** [comment]
@csrwng ptal

**Comment by shalver** [comment]
@csrwng  we need to cherry-pick to release-4.6 as well

**Comment by rtheis** [comment]
@shalver Looks like you will need to do this manually.

**Pull request merged**
