### PR TITLE
Publish release 20220509

### PR DESCRIPTION
**Pull request by jonesbr17**
Pick up base image changes introduced in https://github.com/openshift/release/pull/28381 to remediate CVEs

### CODE REVIEW

**Review by Joseph-Goergen — APPROVED** [review]
/lgtm

**Review by rtheis — CHANGES_REQUESTED** [review]
Let's handle this on Monday and therefore, please change the release date to match.

**Comment by jonesbr17** [comment]
Updated to use today's date (05/09)

**Pull request merged**
