### PR TITLE
support multiarch image as param for release info

### PR DESCRIPTION
**Pull request by yussufsh**

### CODE REVIEW

**Review by rtheis — CHANGES_REQUESTED** [review]
/hold for an explanation of why this is needed since IBM doesn't support a multiarch version of the toolkit at the moment.

**Comment by rtheis** [comment]
@yussufsh can you please provide more information as requested?

**Comment by yussufsh** [comment]
> /hold for an explanation of why this is needed since IBM doesn't support a multiarch version of the toolkit at the moment.

The toolkit can run on x86 but when using multi-arch release images `oc` just fails to recognize the manifest list. However I also think in future when using multi-arch images we would be focusing on hypershift as it already has support for it.

I will close this PR for now as not needed currently.

**Pull request closed without merging**
