### PR TITLE
Update defaultMode 0640 for all secret volume definitions: release-4.6

### PR DESCRIPTION
**Pull request by shalver**
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2037

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by csrwng** [comment]
/approve
/lgtm
@rtheis not sure why you tagging this PR is not working, you are now in the OWNERS file for every release branch. My only theory is that maybe the PR was created before the OWNERS file merged.

**Pull request merged**
