### PR TITLE
Increase KCM node-monitor-grace-period

### PR DESCRIPTION
**Pull request by jmcmeek**
There are couple of known cases where a brief network interruption causes connections to go bad and eventually trigger the KCM to mark the node NotReady:

- The default HTTP2 keepalive settings can leave kubelet using a bad connection for 45s
- The default kube-apiserver etcd3 client grpc keepalive settings can take up to 40s to detect the etcd server it is connected to has gone down - which in turn causes a node in KCM to not see node lease renewal until the kube-apiserver has recovered the etcd connection.

This commit supports setting the KCM node-monitor-grace-period to a value > 45s to address those cases.

Partially implements https://github.ibm.com/alchemy-containers/armada-update/issues/5608

### CODE REVIEW

**Comment by jmcmeek** [comment]
Testing notes:

- [x] Confirm kcm deployment includes `--node-monitor-grace-period` when `nodeMonitorGracePeriod` is specified in the cluster.yaml:
    ~~~
        - "--leader-elect-renew-deadline=107s"
        - "--leader-elect-retry-period=26s"
        - "--node-monitor-grace-period=50s"
        - "--profiling=false"
        - "--root-ca-file=/etc/kubernetes/config/root-ca.crt"
    ~~~

- [x] Confirm kcm deployment is unchanged if `nodeMonitorGracePeriod` not specified:
    ~~~
        - "--leader-elect-renew-deadline=107s"
        - "--leader-elect-retry-period=26s"
        - "--profiling=false"
        - "--root-ca-file=/etc/kubernetes/config/root-ca.crt"
    ~~~

- [x] Include test toolkit release in a ROKS test BOM. Confirm `kube-controller-manager` starts and is configured properly:
    ~~~
    $ ic ks cluster create classic -name jmcmeek -version 4.15.11_1164_openshift -zone dal10 -flavor b3c.4x16 -workers 3 -private-vlan 3415477 -public-vlan 3415475
    Creating cluster...
    OK
    Cluster created with ID cp69sd6100dkhm7jr5qg
    
    $ kubectl get deploy -n master-cp69sd6100dkhm7jr5qg kube-controller-manager
    NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
    kube-controller-manager   3/3     3            3           3m28s
    
    $ kubectl get deploy -n master-cp69sd6100dkhm7jr5qg kube-controller-manager -o yaml
    
        - --leader-elect-renew-deadline=107s
        - --leader-elect-retry-period=26s
        - --node-monitor-grace-period=50s
        - --profiling=false
        - --root-ca-file=/etc/kubernetes/config/root-ca.crt
    ~~~

**Review by rtheis — APPROVED** [review]
/lgtm
/approved

**Comment by rtheis** [comment]
@jmcmeek I suspect that you will need to manually cherry-pick the commit to 4.15 and all earlier releases.

**Pull request merged**
