### PR TITLE
Add ROKS 4.8 API Alert

### PR DESCRIPTION
**Pull request by SmithaSubbarao**
Related to this issue to add the Prometheus API alert to ROKS 4.8: https://github.ibm.com/alchemy-containers/armada-update/issues/2902 and this PR: https://github.com/openshift/ibm-roks-toolkit/pull/457/files

**DNM until test results have been posted below**

### CODE REVIEW

**Comment by SmithaSubbarao** [comment]
Correcting the source file

**Review by rtheis — APPROVED** [review]
/lgtm
/approved

**Comment by SmithaSubbarao** [comment]
Test information: 

Test BOM: https://alchemy-containers-jenkins.swg-devops.com/job/Containers-Runtime/job/armada-test-bom-publish/8952/

Test release: https://github.com/SmithaSubbarao/ibm-roks-toolkit/releases/tag/v2.0-roks4.8-api-alert

Test clusters:

**Comment by SmithaSubbarao** [comment]
ROKS 4.8 test cluster has been created based on this toolkit release: https://github.com/SmithaSubbarao/ibm-roks-toolkit/releases/tag/v2.0-roks4.8-api-alert

```
roks-4.8-new-apitest   c9a968a10hall1h0nqt0   warning     22 minutes ago   3         Dallas     4.8.35_1252_openshift   Default               classic 
```

**Pull request merged**
