### PR TITLE
[release-4.11] Add namespace and RBAC needed for ingress-to-route

### PR DESCRIPTION
**Pull request by attiss**
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/653

### CODE REVIEW

**Review by rtheis — CHANGES_REQUESTED** [review]
PR tests are failing because bindata does not look to be properly generated.

**Comment by rtheis** [comment]
```
 --- /go/src/github.com/openshift/ibm-roks-toolkit/hack/../pkg/assets/bindata.go	2022-10-04 10:04:35.000000000 +0000
+++ /tmp/tmp.Nmxh8PGuA9	2022-10-04 10:10:34.436047843 +0000
@@ -5962,13 +5962,11 @@ var _bindata = map[string]func() (*asset
 // directory embedded in the file by go-bindata.
 // For example if you run go-bindata on data/... and data contains the
 // following hierarchy:
-//
-//	data/
-//	  foo.txt
-//	  img/
-//	    a.png
-//	    b.png
-//
+//     data/
+//       foo.txt
+//       img/
+//         a.png
+//         b.png
 // then AssetDir("data") would return []string{"foo.txt", "img"}
 // AssetDir("data/img") would return []string{"a.png", "b.png"}
 // AssetDir("foo.txt") and AssetDir("notexist") would return an error
make: *** [verify-bindata] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-04T10:10:34Z"} 
```

**Comment by attiss** [comment]
@rtheis Yeah, I've noticed that yesterday too. Stange, I just do `make build` and it automatically formats like this. Let me update the PR.

**Review by rtheis — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
